### ISSUE TITLE
Commit message prefix question

### ISSUE THREAD

**Issue by juggernate** [markj3d/Red9_StudioPack#12]
Just curious, what does the "!U" mean in front of the commit messages?

**Comment by markj3d** [comment]
!U is an update, generasl stuff

!B is a bug fix

!N is a new feature (although I always forget to use that one ;)

All stem from my P4 days in games

hope that sheds light on it

Mark

On 17 February 2016 at 23:27, Nate Allison <notifications@github.com> wrote:

> Just curious, what does the "!U" mean in front of the commit messages?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/12>.
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by juggernate** [comment]
Ah. Ok. Thanks!
