### ISSUE TITLE
evalManager_switch missing

### ISSUE THREAD

**Issue by DrDardis** [markj3d/Red9_StudioPack#13]
Hi Mark,

I just cloned the repo on a new work machine, and am trying to use animation stabilizing in 2016. It is failing to load "evalManager_switch" (for the undo to register), but is not using the cmds.evaluationManager default in the except statement of evalManagerState (I am assuming, as I never see the log string you have used in the exception), and just stepping back to original time.

Here is the log

```
# Warning: Red9.core.Red9_General : Plugin Failed to load : evalManager_switch # 
# Red9.core.Red9_General : autoKeyState restored: False # 
# Warning: Red9.core.Red9_General : Plugin Failed to load : evalManager_switch # 
# Red9.core.Red9_General : evalManager restored: parallel # 
# Red9.core.Red9_General : currentTime restored: 5630.000000 # 
```

Let me know if I can help further!

Chris

**Comment by markj3d** [comment]
Thanks for the catch, I'll go take a look. The EvalManager stuff is
work-in-progress at the moment, still trying to tame the parallel
environment as it seriously slows down any time enabled function within
Maya.

thanks

mark

On 18 April 2016 at 03:14, Chris Dardis <notifications@github.com> wrote:

> Hi Mark,
>
> I just cloned the repo on a new work machine, and am trying to use
> animation stabilizing in 2016. It is failing to load "evalManager_switch"
> (for the undo to register), but is not using the cmds.evaluationManager
> default in the except statement of evalManagerState (I am assuming, as I
> never see the log string you have used in the exception), and just stepping
> back to original time.
>
> Here is the log;
> Warning: Red9.core.Red9_General : Plugin Failed to load :
> evalManager_switch # Red9.core.Red9_General : autoKeyState restored:
> False # Warning: Red9.core.Red9_General : Plugin Failed to load :
> evalManager_switch # Red9.core.Red9_General : evalManager restored:
> parallel # Red9.core.Red9_General : currentTime restored: 5630.000000 #
>
> Let me know if I can help further!
>
> Chris
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/13>
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by markj3d** [comment]
Hi Chris, can you get latest and try again, I've just moved the plugin from
Pro_Pack over to main as I figure it's best to be at the core level

On 18 April 2016 at 03:14, Chris Dardis <notifications@github.com> wrote:

> Hi Mark,
>
> I just cloned the repo on a new work machine, and am trying to use
> animation stabilizing in 2016. It is failing to load "evalManager_switch"
> (for the undo to register), but is not using the cmds.evaluationManager
> default in the except statement of evalManagerState (I am assuming, as I
> never see the log string you have used in the exception), and just stepping
> back to original time.
>
> Here is the log;
> Warning: Red9.core.Red9_General : Plugin Failed to load :
> evalManager_switch # Red9.core.Red9_General : autoKeyState restored:
> False # Warning: Red9.core.Red9_General : Plugin Failed to load :
> evalManager_switch # Red9.core.Red9_General : evalManager restored:
> parallel # Red9.core.Red9_General : currentTime restored: 5630.000000 #
>
> Let me know if I can help further!
>
> Chris
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/13>
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by DrDardis** [comment]
Awesome Mark, thanks for that! ☺

Will pull now….
