### ISSUE TITLE
Red9_AnimationUtils.py copyAttributes, copy paste error.

### ISSUE THREAD

**Issue by BoubQC** [markj3d/Red9_StudioPack#14]
Hi Mark,

Was reading your code and stumbled upon what looks like a copy paste error.

Check Red9_AnimationUtils.py at line 2921 and 2922.

`                            for attr in attributes:
                                if cmds.attributeQuery(attr, node=src, exists=True) \
                                    and cmds.attributeQuery(attr, node=src, exists=True):
                                    cmds.setAttr('%s.%s' % (dest, attr), cmds.getAttr('%s.%s' % (src, attr)))`

Your condition tests if the attribute exists 2 times on the src object. You probably wanted to test it on the dest node.

By the way thanks for sharing all of that hot stuff.

**Comment by markj3d** [comment]
hhhmm, looks like it yes, that code's been running like that for a long
time now but I'll switch it as it makes no sense to check twice! Thanks!

Mark

On 12 May 2016 at 14:23, Simon Bourassa Blouin <notifications@github.com>
wrote:

> Hi Mark,
>
> Was reading your code and stumbled upon what looks like a copy paste error.
>
> Check Red9_AnimationUtils.py at line 2921 and 2922.
>
> for attr in attributes:
> if cmds.attributeQuery(attr, node=src, exists=True) \
> and cmds.attributeQuery(attr, node=src, exists=True):
> cmds.setAttr('%s.%s' % (dest, attr), cmds.getAttr('%s.%s' % (src, attr)))
>
> Your condition tests if the attribute exists 2 times on the src object.
> You probably wanted to test it on the dest node.
>
> By the way thanks for sharing all of that hot stuff.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/14>
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by markj3d** [comment]
fix submitted thanks

On 12 May 2016 at 14:42, Mark Jackson <markj3d@gmail.com> wrote:

> hhhmm, looks like it yes, that code's been running like that for a long
> time now but I'll switch it as it makes no sense to check twice! Thanks!
>
> Mark
>
> On 12 May 2016 at 14:23, Simon Bourassa Blouin <notifications@github.com>
> wrote:
>
>> Hi Mark,
>>
>> Was reading your code and stumbled upon what looks like a copy paste
>> error.
>>
>> Check Red9_AnimationUtils.py at line 2921 and 2922.
>>
>> for attr in attributes:
>> if cmds.attributeQuery(attr, node=src, exists=True) \
>> and cmds.attributeQuery(attr, node=src, exists=True):
>> cmds.setAttr('%s.%s' % (dest, attr), cmds.getAttr('%s.%s' % (src, attr)))
>>
>> Your condition tests if the attribute exists 2 times on the src object.
>> You probably wanted to test it on the dest node.
>>
>> By the way thanks for sharing all of that hot stuff.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/markj3d/Red9_StudioPack/issues/14>
>>
>
>
>
> --
> -------------------------------------
> Mark Jackson
> CEO / Technical Director
> red9consultancy.com
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by BoubQC** [comment]
Great thanks!
