### ISSUE TITLE
Host docs on Github Pages

### ISSUE THREAD

**Issue by matthewkapfhammer** [markj3d/Red9_StudioPack#16]
Quick and dirty example:
https://matthewkapfhammer.github.io/Red9_StudioPack/#

I can do the "clean" pass and submit a pull request if you're interested. It merely adds a new branch to the repo. Initially, that will be good enough. 

Ideally, we would also create a main page with links to the docs for each released version. Again, happy to do that if you're interested. 

Cheers,
Matthew

**Comment by markj3d** [comment]
Hi Mathew, certainly sounds interesting, we were looking at hosting the docs under our new web-site when it's finally live, along with a forum for the toolsets,  but having it on Github might be a nice option.

The GitHub build has fallen behind our dev trunk as we now have an internal repository for both StudioPack and ProPack / Client code and I need to make sure I commit back to this repository!! Still lots of new code going in as the StuidoPack is still very much the core of all our code...

**Comment by matthewkapfhammer** [comment]
Hi Mark!

As long as there's a link to the docs from this repo, it doesn't really matter where they are hosted. The only plus I can see from hosting on Github is that others can more easily help update the docs. 

When do you expect to update here?

**Comment by matthewkapfhammer** [comment]
I see an update! :) 

If I generate the docs and push them to a gh-pages branch, will you accept the pull request?
