### ISSUE TITLE
MetaClass method: nameSpace() list index out of range when MetaClass node is in 'root' namespace

### ISSUE THREAD

**Issue by dshlai** [markj3d/Red9_StudioPack#4]
``` python
#   File "U:\tools\Red9\core\Red9_Meta.py", line 1938, in nameSpace
#     return ns[:-1][0]
# IndexError: list index out of range # 
```

nameSpaceFull() works for nodes in 'root' namespace, but nameSpace() will have the above error. Both methods work when node is in some namespace.

**Comment by markj3d** [comment]
Good catch Dennis,  I'll drop a patch for that today.  Dud you see the mods
to the language stuffr I did?

**Comment by dshlai** [comment]
Yes, I just rebase your latest commits (I was using the older forked version), I notice the language mapping when I import the Red9 root module. I will put the Chinese language map development onto a separate branch so I will track your latest commits better in the future. 

BTW, The JSON serialize/deserialize stuff in the Maya node attribute is neat. I can use that to store a lot of pipeline metadata in a standardized way. Since YAML has almost the same API as json, it should be possible to implement YAML serialize/deserialize in Maya node as well.

**Comment by markj3d** [comment]
Cool, The namespace issue is now fixed. The JSON attr handler has been a
massive help for our pipeline, just to be able to serialize big chunks of
data to nodes is really powerful. We use it for the MetaRig stuff to store
bindPose's and attrMaps, as well as in the SceneReview code to store
comments out to an attr.

I'll take a look at your Chinese map file, might look to integrate that
back into the build at some point if you're ok with that.

cheers
Mark

On 20 April 2015 at 19:31, dshlai <notifications@github.com> wrote:

> Yes, I just rebase your latest commits (I was using the older forked
> version), I notice the language mapping when I import the Red9 root module.
> I will put the Chinese language map development onto a separate branch so I
> will track your latest commits better in the future.
>
> BTW, The JSON serialize/deserialize stuff in the Maya node attribute is
> neat. I can use that to store a lot of pipeline metadata in a standardized
> way. Since YAML has almost the same API as json, it should be possible to
> implement YAML serialize/deserialize in Maya node as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/4#issuecomment-94531959>
> .
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by dshlai** [comment]
The language map is not finished yet (WIP). I will do a pull request when I think it's ready. We are using Shotgun in our studio as well, I think I can actually store some of these JSON data (probably not the heavy duty like bindPose and attrMaps, but stuff like asset information, artist name, create/update time, comments, etc.) in Shotgun as well when the artist do a publish, so other people (for example, managers and coordinators) who are not necessary using Maya will also have a way to see these data.

One other cool way I thought that would help in the asset pipeline is to store JSON data as an extra attribute when exporting Alembic cache/geometry. This might allow some form of data exchange between 3D apps

**Comment by markj3d** [comment]
Cool, I'll look out for that pull, be great to get it all full compliant
with Chinese but even the basics would be a good start. Thanks Dennis

On 20 April 2015 at 20:22, dshlai <notifications@github.com> wrote:

> The language map is not finished yet (WIP). I will do a pull request when
> I think it's ready. We are using Shotgun in our studio as well, I think I
> can actually store some of these JSON data (probably not the heavy duty
> like bindPose and attrMaps, but stuff like asset information, artist name,
> create/update time, comments, etc.) in Shotgun as well when the artist do a
> publish, so other people (for example, managers and coordinators) who are
> not necessary using Maya will also have a way to see these data.
>
> One other cool way I thought that would help in the asset pipeline is to
> store JSON data as an extra attribute when exporting Alembic
> cache/geometry. This might allow some form of data exchange between 3D apps
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/4#issuecomment-94546103>
> .
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com
