### ISSUE TITLE
Pro Pack import error

### ISSUE THREAD

**Issue by mdilena** [markj3d/Red9_StudioPack#5]
Since last pull, when I open Maya, I get an ImportError:

```
# Error: No module named pro_pack
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
# ImportError: No module named pro_pack #
```

I do not own pro edition, but never had this error before.
Cheers!

**Comment by markj3d** [comment]
Yes sorry about that one, it was a bug in our wrapping of ProPack
integration, just submitting the patch now ;)

On 26 June 2015 at 08:34, matteodilena <notifications@github.com> wrote:

> Since last pull, when I open Maya, I get an ImportError:
> Error: No module named pro_pack Traceback (most recent call last): File
> "", line 1, in ImportError: No module named pro_pack
>
> I do not own pro edition, but never had this error before.
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/5>.
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by matteodilena** [comment]
Oh god, why the text is so huge?
Anyway, thanks for the quick patch mark :)

**Comment by markj3d** [comment]
no worries, I caught it on Friday just forgot to submit the code!

On 26 June 2015 at 08:41, matteodilena <notifications@github.com> wrote:

> Oh god, why the text is so huge?
> Anyway, thanks for the quick patch mark :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/5#issuecomment-115563756>
> .
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by matteodilena** [comment]
Mhh, I got the patch but it is still happening

**Comment by markj3d** [comment]
try again, get latest

On 26 June 2015 at 08:52, matteodilena <notifications@github.com> wrote:

> Mhh, I got the patch but it is still happening
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/5#issuecomment-115565131>
> .
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com

**Comment by matteodilena** [comment]
Perfect, thank you again Mark!

**Comment by markj3d** [comment]
markj3d
