### ISSUE TITLE
pymel nodes support

### ISSUE THREAD

**Issue by juggernate** [markj3d/Red9_StudioPack#9]
Are there plans for pymel node support? I use pymel PyNodes most of the time but have to cast out to work with Red9.

**Comment by markj3d** [comment]
I was working on a decorator to allow PyNodes as inputs and ensure returns were always instantiated PyNodes but never got chance to finish or test it. I'm assuming you're talking about metaData module here?

**Comment by juggernate** [comment]
Yes, for metaData. I saw the decorator, but it didn't appear to be finished. If you are not planning on it in the near future I might try implementing it on my fork. If I did would you care for me to open a pull request?

**Comment by markj3d** [comment]
Hi Nate, no I never had the chance to finish looking into the PyMel
support, primarily as I think it's a bigger issue than just a decorator but
I may be wrong. If you do take a look at it and get it running then by all
means pass it over, be interesting to see what you do

thanks

mark

On 16 September 2015 at 16:11, Nate Allison <notifications@github.com>
wrote:

> Yes, for metaData. I saw the decorator, but it didn't appear to be
> finished. If you are not planning on it in the near future I might try
> implementing it on my fork. If I did would you care for me to open a pull
> request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markj3d/Red9_StudioPack/issues/9#issuecomment-140771855>
> .
>



-- 
-------------------------------------
Mark Jackson
CEO / Technical Director
red9consultancy.com
